# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0002_auto_20170908_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinator',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='employee',
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name_plural': 'Empleados'},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='academicunit',
        ),
        migrations.AddField(
            model_name='employee',
            name='academic_unit',
            field=models.CharField(blank=True, max_length=50, verbose_name='nombre unidad académica'),
        ),
        migrations.AddField(
            model_name='employee',
            name='academic_unit_webpage',
            field=models.CharField(blank=True, max_length=50, verbose_name='unidad académica - página web'),
        ),
        migrations.AddField(
            model_name='employee',
            name='category',
            field=models.CharField(blank=True, max_length=50, verbose_name='categoría'),
        ),
        migrations.AddField(
            model_name='employee',
            name='course',
            field=models.CharField(blank=True, max_length=20, verbose_name='curso'),
        ),
        migrations.AddField(
            model_name='employee',
            name='curriculum',
            field=models.CharField(blank=True, max_length=50, verbose_name='currículo'),
        ),
        migrations.AddField(
            model_name='employee',
            name='grade',
            field=models.CharField(blank=True, max_length=20, verbose_name='título'),
        ),
        migrations.AddField(
            model_name='employee',
            name='program',
            field=models.CharField(blank=True, max_length=50, verbose_name='programa'),
        ),
        migrations.AddField(
            model_name='employee',
            name='program_description',
            field=models.CharField(blank=True, max_length=20, verbose_name='descripción'),
        ),
        migrations.AddField(
            model_name='employee',
            name='snies',
            field=models.CharField(blank=True, max_length=20, verbose_name='snies'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='nombre'),
        ),
        migrations.DeleteModel(
            name='AcademicUnit',
        ),
        migrations.DeleteModel(
            name='Coordinator',
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
    ]
