# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0004_auto_20170910_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='category',
            field=models.CharField(blank=True, max_length=100, verbose_name='categoría'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='course',
            field=models.CharField(blank=True, max_length=100, verbose_name='curso'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='curriculum',
            field=models.CharField(blank=True, max_length=100, verbose_name='currículo'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.CharField(blank=True, max_length=100, verbose_name='correo'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='grade',
            field=models.CharField(blank=True, max_length=100, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='program',
            field=models.CharField(blank=True, max_length=100, verbose_name='programa'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='program_description',
            field=models.CharField(blank=True, max_length=100, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(blank=True, max_length=100, verbose_name='cargo'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='webpage',
            field=models.CharField(blank=True, max_length=100, verbose_name='página Web'),
        ),
    ]
