# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20170909_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'Noticias'},
        ),
    ]
