# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 22:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20170910_1721'),
        ('news', '0003_auto_20170910_1828'),
    ]

    operations = [
    ]
