# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20170910_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(blank=True, verbose_name='descripción'),
        ),
    ]
