# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20170910_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='link',
            field=models.TextField(blank=True, verbose_name='enlace'),
        ),
    ]
