# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 01:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20170910_2232'),
        ('news', '0004_merge_20170910_2248'),
    ]

    operations = [
    ]
