# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-07 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
                ('webpage', models.CharField(max_length=50, verbose_name='página web')),
            ],
            options={
                'verbose_name_plural': '01. Unidades Académicas',
            },
        ),
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(blank=True, max_length=50, verbose_name='Programe')),
                ('snies', models.CharField(blank=True, max_length=20, verbose_name='snies')),
                ('description', models.CharField(blank=True, max_length=20, verbose_name='descripción')),
            ],
            options={
                'verbose_name_plural': '04. Coordinadores',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
                ('email', models.CharField(blank=True, max_length=50, verbose_name='correo')),
                ('position', models.CharField(blank=True, max_length=50, verbose_name='cargo')),
                ('local', models.CharField(blank=True, max_length=20, verbose_name='oficina')),
                ('extension', models.CharField(blank=True, max_length=10, verbose_name='extension')),
                ('webpage', models.CharField(blank=True, max_length=50, verbose_name='página Web')),
                ('gscholar', models.CharField(blank=True, max_length=50, verbose_name='google scholar')),
                ('facebook', models.CharField(blank=True, max_length=20, verbose_name='facebook')),
                ('twitter', models.CharField(blank=True, max_length=20, verbose_name='twitter')),
                ('academicunit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='professor.AcademicUnit')),
            ],
            options={
                'verbose_name_plural': '02. Empleados',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculum', models.CharField(blank=True, max_length=50, verbose_name='currículo')),
                ('grade', models.CharField(blank=True, max_length=20, verbose_name='título')),
                ('course', models.CharField(blank=True, max_length=20, verbose_name='título')),
                ('category', models.CharField(blank=True, choices=[('P', 'PLANTA'), ('C', 'CATEDRA')], default='C', max_length=1, verbose_name='categoría')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professor', to='professor.Employee')),
            ],
            options={
                'verbose_name_plural': '03. Profesores',
            },
        ),
        migrations.AddField(
            model_name='coordinator',
            name='professor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coordinator', to='professor.Professor'),
        ),
    ]
